platform :ios, '9.0'

use_frameworks!
project 'jpushdemo.xcworkspace'
target 'jpushdemo' do
    pod 'JPushRN', :path => '../node_modules/jpush-react-native'
end

swift4 = ['Charts']

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if swift4.include?(target.name)
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
    end
  end
end